### ISSUE TITLE
license

### ISSUE THREAD

**Issue by jdsika** [teztok/indexer#17]
Hi all,

Love the project! Do you already know when you decide on a license? Any ideas on its properties? 

How do you feel about potential contributions to your project?

Best regards
Carlo

**Comment by xat** [comment]
Hi Carlo,

thanks for your interest :)

yes, we have postponed the license discussion a couple of times, because we don't want to choose something that will bite us later.

what we want from the license is that users are able to operate a teztok instance. changes made to the indexer should be open-sourced as well. on the same hand, we don't want the license to be too invasive, so it shouldn't require a user to open-source any code that is not directly related to the indexer. hope that helps :)

we welcome contributions. if it's a bigger contribution that involves potentially controversial aspects, it's best to describe the planned changes up-front in a GitHub issue.

greetings,

Simon

**Comment by jdsika** [comment]
There are basically "endless" options for in your case "non copy left" licenses. It is always helpful to look around you in the ecosystem and explore what others pieces of software use that you are potentially using as dependencies. In this case you will find one dominant one (also the Tezos Octez node) [MIT](https://mit-license.org/) license. It is the most common (?) license and is basically a "do whatever the heck you want with it" license. The other option would be [Apache-2.0](https://www.apache.org/licenses/LICENSE-2.0.html) which e.g. Tezos Profiles uses. I suggest to just read both and see what "feels better". IMO both are suitable whereas Apache is a bit more explicit. See [this](https://tldrlegal.com/license/apache-license-2.0-%28apache-2.0%29) for an explanation of the obligations in "plain english".

**Comment by xat** [comment]
appreciate your feedback.

MIT is what I use for all my other open source projects, where i don't care how others use/modify the code.

with teztok, we do want others to open-source any modifications they make to the indexer, so i wouldn't label the requirement as "non copyleft", probably more some sort of "weak copyleft".

maybe the Mozilla Public License 2.0 could be an option, for example.

**Comment by jdsika** [comment]
ahhh I misinterpreted this "we don't want the license to be too invasive" 

yes, [MPL-2.0](https://www.mozilla.org/en-US/MPL/2.0/) is a very good license regarding your requirement. It has (to my knowledge) two "weak copy left components" - here is the [FAQ](https://www.mozilla.org/en-US/MPL/2.0/FAQ/)
1. If you contribute into the same file you need to put your contribution under the same license again (MPL-2.0)
2. If you use the software in a modified version you need to distribute the code along with it if the use is outside of your organization

I am typically using MPL-2.0 for standard interfaces like e.g. the [Open Simulation interface](https://github.com/OpenSimulationInterface/open-simulation-interface). Maybe you have to check for [compatibility](https://opensource.com/law/11/9/mpl-20-copyleft-and-license-compatibility)

**Comment by xat** [comment]
the thing that makes me a bit unsure about MPL is the part where you only have to open-source modified source files and not any newly added files, which creates a bit of a loophole.

maybe a solution to this could be to compile the source code (excluding node_modules) from typescript into a single unminified-javascript file and then to add the license to that file. unfortunately, we would then always need to commit that file along with the other source files.

**Comment by jdsika** [comment]
Eventually I personally think that the license tells the user/contributor what is expected of him and what is "right" - if someone wants to cheat he will... It would be best to think about the incentive to contribute to a single project and share instead of trying to do "license gymnastics" :)

The number one goal is to make it useable and create a network effect regarding contributions. People and companies need to be safe using it.

I would avoid trying to be "too clever" but instead clear open and honest.

Give it a code of conduct, explain your intend and take the license that is closest but do not try to think to hard about ways on how others can outsmart you

**Comment by xat** [comment]
yeah, i agree with what you are saying. i'm also not a huge fan of being too protective.

the main reason for open sourcing the code is that users know that someone else is able to pickup the code and operate the indexer if our service ever shuts down and to also give those users an option who don't trust central services and prefer running their own instance (maybe with some slight modifications).

we spent a lot of time creating the indexer, so far without any funding or other income. so i'm a bit afraid of well funded companies using the code as a core part in their infrastructure, without contributing back either financially or by open sourcing their modifications.

ideally, the license allows users to use and extend the code how they want, as long as they open-source the modifications. if they don't want to open-source the modifications, they can reach out to us and we will find another kind of agreement/solution.

**Comment by jdsika** [comment]
In the past years I learned to look reality in the eyes. Just one example is the [Tezos Reward Distributor](https://github.com/tezos-reward-distributor-organization/tezos-reward-distributor) for which I act as a maintainer. The majority of bakers use it and the biggest among them do not contribute but sometimes send irritating emails in which they "demand" something to fixed or feature XY. They consume instead of adding to its value - on the other hand over the past 5 (?) years there have always been fantastic individuals saving the day and making major code contributions, onboarding others, helping out in slack, testing features etc etc. 
Without them the project would have most likely died and I myself as a user would have been overwhelmed by the amount of work I could never have handled myself. I suggest you have a look at the way we use a TF grant in a multisig wallet to incentivize code contributions!

In other projects in the automotive industry e.g. contributions to open source are only depending on the license in the sense that everyone checks "am I safe using it and are there any traps" - If a license is modified or additional individual and hard to comply with or understandable clauses are added the projects they are just not used. But their use is the number one goal. After this check the structure and how work and contributions are organized is very important for active participants as well as the "spirit of the project".

Thus, I think the license matters in a sense that it must encourage usage in making it safe for the user. Open source does expose you and your work for a long shot of creating a community that is engaging and bringing you benefits mid term. 

What you are saying is more pointing in the direction of [LGPL](https://en.wikipedia.org/wiki/GNU_Lesser_General_Public_License) BUT maybe making it MIT and e.g. letting the project participate this [hackathon](https://twitter.com/XTZNews/status/1529778920689647620?s=20&t=FkP7gbekE1-mqG8EhXjr_w) making it popular by winning and getting funding for it e.g. the way TRD does it will make you less problems and lets you concentrate on figuring out a proper value proposition for the project as part of a service others would want to use?

**Comment by xat** [comment]
once again appreciate your perspective :)

TRD looks nice. i'm also considering to become a baker, now that the tax situation in germany is cleared. and yeah, users can be very demanding (paying users usually value your time more, though).

tbh, so far i just assumed that the work on the codebase would mainly have to be done by myself. new nft marketplaces pop up on tezos quite frequently and every once in a while marketplaces release new versions of their contracts. keeping up with that + implementing the features planned/requested + user support + docs and creating examples is basically a full-time job.

we are currently in the process of applying for a grant. i think the outcome of this also has an influence on the direction the project will take and therefore the license. personally i would love to just slap a MIT license on the project and call it a day

**Comment by jdsika** [comment]
Just send me a message when you need support setting up TRD @jdsika is working on basically every Plattform :)

Did you consider the hackathon? It could be great for visibility. 

I will evaluate the this project as well with the team. I see it on the agenda in 1-2months.
Should I keep this issue open until there is a decision?

**Comment by xat** [comment]
hackathon looks interesting, but I'm currently on vacation until 11th of june. I'm also not sure if the teztok indexer would fit the format since it's a project that i already spent multiple months developing on and that is used by several projects in production.

imho we can keep the issue open, then it's visible to others who are also wondering about the status of the license.

**Comment by xat** [comment]
looked a bit deeper into the hackathon. it would be fun to participate :) the teztok indexer itself probably isn't a good fit for the format, but maybe a demo that is built on top of it.

i'll need to check if it's still possible to participate when i'm back from vacation or if it's too late by then.

**Comment by xat** [comment]
it's now licensed under MIT. let's hope this is the right decision :-)

**Comment by jdsika** [comment]
I guess it is fine :)
