### ISSUE TITLE
Add a rightsUri field to the token table to handle the typo in TZIP-21

### ISSUE THREAD

**Issue by Zir0h** [teztok/indexer#61]
So apparently there's a typo in TZIP-21... :/

rightUri should be right**s**Uri, now we already have a couple of tokens with the incorrect (164 in case of Teia and 55630 on api.teztok.com)

I would like to align the metadata field for all tokens. Would it be possible to add a rights_uri to the indexer for new mints, and keep right_uri for the older tokens?

See also:
https://gitlab.com/tezos/tzip/-/issues/4647#note_2001912118
https://gitlab.com/tezos/tzip/-/merge_requests/221
and the conversation between marshingsquare and me on the teia discord server in general-dev

**Comment by xat** [comment]
handled in https://github.com/teztok/indexer/pull/62
