### ISSUE TITLE
New CORS issue

### ISSUE THREAD

**Issue by Anaglyph-ic** [teztok/indexer#66]
I'm trying to request the API from a github page (I don't have a back-end for my app). Here is what it now yields (it used to work).

```
Access to XMLHttpRequest at 'https://api.teztok.com/v1/graphql' from origin 'https://anaver.se' has been 
blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by xat** [comment]
Hmm, I can't tell. Had a quick look at the projects we built back in the day, which technically also make requests to the API from a different (sub-)domain. They are working fine.

**Comment by Anaglyph-ic** [comment]
This apparently solved itself, I'm not bumping into that problem anymore. Thanks!
